### PR TITLE
To have correct directions when using /dev/input/eventx

### PR DESCRIPTION
**Pull request by marcopiraccini**
...with "arcade" settings

### CODE REVIEW

**Comment by petrockblog** [comment]
Thanks!

**Comment by a7mag3ddon** [comment]
Hello, this still doesn't work. have the changes been applied yet? Daphne movement controls are still revered. as of 28/02 :

**Comment by petrockblog** [comment]
You can see from the information above that the pull request was merged on 7 Jan in commit https://github.com/petrockblog/ControlBlockService2/commit/dec84ea4d8d8130bf42c85b94dbc0f889d12747f.

**Comment by a7mag3ddon** [comment]
so its that a no then?

**Comment by petrockblog** [comment]
It means that the changes have been applied. If that does not solve the issue with Daphne, you might want to try to switch to gamepadtype "mame". Maybe that helps?

**Comment by marcopiraccini** [comment]
@a7mag3ddon are you sure you correctly updated the build? 
However, you can do a test with `jstest` moving the joystick in all directions and put here the results

**Pull request merged**
